default_stages: [push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-vcs-permalinks
      - id: end-of-file-fixer
        exclude: "tests/((commands|data)/|test_).+"
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: debug-statements
      - id: no-commit-to-branch

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.28.1 # automatically updated by Commitizen
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: format
        name: format
        language: system
        pass_filenames: false
        entry: ./scripts/format
        types: [python]

      - id: linter and test
        name: linter and test
        language: system
        pass_filenames: false
        entry: ./scripts/test
        types: [python]
