site_name: Commitizen
site_description: commit rules, semantic version, conventional commits

theme:
  name: "material"
  palette:
    - primary: 'deep purple'
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

repo_name: commitizen-tools/commitizen
repo_url: https://github.com/commitizen-tools/commitizen
edit_uri: ""

nav:
  - Introduction: "README.md"
  - Getting Started: "getting_started.md"
  - Commands:
      - init: "commands/init.md"
      - commit: "commands/commit.md"
      - bump: "commands/bump.md"
      - check: "commands/check.md"
      - changelog: "commands/changelog.md"
      - example: "commands/example.md"
      - info: "commands/info.md"
      - ls: "commands/ls.md"
      - schema: "commands/schema.md"
      - version: "commands/version.md"
  - Configuration: "config.md"
  - Customization: "customization.md"
  - Tutorials:
      - Writing commits: "tutorials/writing_commits.md"
      - Managing tags formats: "tutorials/tag_format.md"
      - Auto check commits: "tutorials/auto_check.md"
      - Auto prepare commit message: "tutorials/auto_prepare_commit_message.md"
      - GitLab CI: "tutorials/gitlab_ci.md"
      - Github Actions: "tutorials/github_actions.md"
      - Jenkins pipeline: "tutorials/jenkins_pipeline.md"
      - Developmental releases: "tutorials/dev_releases.md"
      - Monorepo support: "tutorials/monorepo_guidance.md"
  - FAQ: "faq.md"
  - Exit Codes: "exit_codes.md"
  - Third-Party Commitizen Templates: "third-party-commitizen.md"
  - Contributing: "contributing.md"
  - Resources: "external_links.md"

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
