name: Publish documentation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update-cli-screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install -U pip poetry poethepoet
          poetry --version
          poetry install --only main,script
      - name: Update CLI screenshots
        run: |
          poetry doc:screenshots
      - name: Commit and push updated CLI screenshots
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/images/cli_help

          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "docs(cli/screenshots): update CLI screenshots" -m "[skip ci]"
            git push
          else
            echo "No changes to commit. Skipping."
          fi

  publish-documentation:
    runs-on: ubuntu-latest
    needs: update-cli-screenshots
    steps:
      - uses: actions/checkout@v5
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0
      - name: Pull latest changes
        run: |
          git pull origin master
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install -U pip poetry poethepoet
          poetry --version
          poetry install --no-root --only documentation
      - name: Generate Sponsors ðŸ’–
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_ORG }}
          file: "docs/README.md"
          organization: true
      - name: Build docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry doc:build
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./site # The folder the action should deploy.
          branch: gh-pages
